version: '3'

services:
  db:
    image: postgres
    container_name: db
    tty: true
    networks:
      - pong_network
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    build:
      context: ./backend
    image: backend:transcendence
    container_name: backend
    networks:
      - pong_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    expose:
      - "3000"
    ports:
      - "8080:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    image: frontend:transcendence
    container_name: frontend
    networks:
      - pong_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres:


networks:
  pong_network:
    driver: bridge
