version: '3'

services:
  db:
    image: postgres
    container_name: db
    tty: true
    networks:
      - transcendence
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    build:
      context: ./backend
    image: backend
    container_name: backend
    networks:
      - transcendence
    environment:
      - APP_PORT=8080
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://backend:8080
        - GATEWAY_URL=http://localhost:8080
    image: frontend
    container_name: frontend
    networks:
      - transcendence
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres:

networks:
  transcendence:
    driver: bridge
