version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    tty: true
    networks:
      - transcendence
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    build:
      context: ./backend
    image: backend
    container_name: backend
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    image: frontend
    container_name: frontend
    networks:
      - transcendence
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres:

networks:
  transcendence:
    driver: bridge
